// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
 export default [
  {
    "key": "api",
    "zh-CN": "API",
    "en-US": "API"
  },
  {
    "key": "api_array",
    "zh-CN": "数组",
    "en-US": "Array"
  },
  {
    "key": "api_array_fill",
    "zh-CN": "fill",
    "en-US": "fill"
  },
  {
    "key": "api_array_get",
    "zh-CN": "get",
    "en-US": "get"
  },
  {
    "key": "api_array_get-size",
    "zh-CN": "getSize",
    "en-US": "getSize"
  },
  {
    "key": "api_array_length",
    "zh-CN": "length",
    "en-US": "length"
  },
  {
    "key": "api_array_pop",
    "zh-CN": "pop",
    "en-US": "pop"
  },
  {
    "key": "api_array_push",
    "zh-CN": "push",
    "en-US": "push"
  },
  {
    "key": "api_array_remove-visual",
    "zh-CN": "removeVisual",
    "en-US": "removeVisual"
  },
  {
    "key": "api_array_reverse",
    "zh-CN": "reverse",
    "en-US": "reverse"
  },
  {
    "key": "api_array_set",
    "zh-CN": "set",
    "en-US": "set"
  },
  {
    "key": "api_array_set-state",
    "zh-CN": "setState",
    "en-US": "setState"
  },
  {
    "key": "api_array_set-visual",
    "zh-CN": "setVisual",
    "en-US": "setVisual"
  },
  {
    "key": "api_array_shift",
    "zh-CN": "shift",
    "en-US": "shift"
  },
  {
    "key": "api_array_sort",
    "zh-CN": "sort",
    "en-US": "sort"
  },
  {
    "key": "api_array_splice",
    "zh-CN": "splice",
    "en-US": "splice"
  },
  {
    "key": "api_array_swap",
    "zh-CN": "swap",
    "en-US": "swap"
  },
  {
    "key": "api_array_unshift",
    "zh-CN": "unshift",
    "en-US": "unshift"
  },
  {
    "key": "api_graph",
    "zh-CN": "图",
    "en-US": "Graph"
  },
  {
    "key": "api_graph_add-adjacency-link",
    "zh-CN": "addAdjacencyLink",
    "en-US": "addAdjacencyLink"
  },
  {
    "key": "api_graph_create-graph",
    "zh-CN": "createGraph",
    "en-US": "createGraph"
  },
  {
    "key": "api_graph_create-node",
    "zh-CN": "createNode",
    "en-US": "createNode"
  },
  {
    "key": "api_graph_find-node",
    "zh-CN": "findNode",
    "en-US": "findNode"
  },
  {
    "key": "api_graph_start-layout",
    "zh-CN": "startLayout",
    "en-US": "startLayout"
  },
  {
    "key": "api_linked-list",
    "zh-CN": "链表",
    "en-US": "Linkd List"
  },
  {
    "key": "api_linked-list_create-node",
    "zh-CN": "createNode",
    "en-US": "createNode"
  },
  {
    "key": "api_linked-list_get-next",
    "zh-CN": "getNext",
    "en-US": "getNext"
  },
  {
    "key": "api_linked-list_link",
    "zh-CN": "link",
    "en-US": "link"
  },
  {
    "key": "api_linked-list_remove",
    "zh-CN": "remove",
    "en-US": "remove"
  },
  {
    "key": "api_linked-list_set-next",
    "zh-CN": "setNext",
    "en-US": "setNext"
  },
  {
    "key": "api_linked-list_unlink",
    "zh-CN": "unlink",
    "en-US": "unlink"
  },
  {
    "key": "api_queue",
    "zh-CN": "队列",
    "en-US": "Queue"
  },
  {
    "key": "api_queue_add",
    "zh-CN": "add",
    "en-US": "add"
  },
  {
    "key": "api_queue_element",
    "zh-CN": "element",
    "en-US": "element"
  },
  {
    "key": "api_queue_remove",
    "zh-CN": "remove",
    "en-US": "remove"
  },
  {
    "key": "api_stack",
    "zh-CN": "栈",
    "en-US": "Stack"
  },
  {
    "key": "api_stack_is-empty",
    "zh-CN": "isEmpty",
    "en-US": "isEmpty"
  },
  {
    "key": "api_stack_pop",
    "zh-CN": "pop",
    "en-US": "pop"
  },
  {
    "key": "api_stack_push",
    "zh-CN": "push",
    "en-US": "push"
  },
  {
    "key": "api_stack_top",
    "zh-CN": "top",
    "en-US": "top"
  },
  {
    "key": "api_tree",
    "zh-CN": "树",
    "en-US": "Tree"
  },
  {
    "key": "api_tree_append",
    "zh-CN": "append",
    "en-US": "append"
  },
  {
    "key": "api_tree_clear",
    "zh-CN": "clear",
    "en-US": "clear"
  },
  {
    "key": "api_tree_create-node",
    "zh-CN": "createNode",
    "en-US": "createNode"
  },
  {
    "key": "api_tree_create-tree",
    "zh-CN": "createTree",
    "en-US": "createTree"
  },
  {
    "key": "api_tree_get-children",
    "zh-CN": "getChildren",
    "en-US": "getChildren"
  },
  {
    "key": "api_tree_get-data",
    "zh-CN": "getData",
    "en-US": "getData"
  },
  {
    "key": "api_tree_insert",
    "zh-CN": "insert",
    "en-US": "insert"
  },
  {
    "key": "api_tree_remove",
    "zh-CN": "remove",
    "en-US": "remove"
  },
  {
    "key": "api_tree_remove-visual",
    "zh-CN": "removeVisual",
    "en-US": "removeVisual"
  },
  {
    "key": "api_tree_reverse",
    "zh-CN": "reverse",
    "en-US": "reverse"
  },
  {
    "key": "api_tree_set-data",
    "zh-CN": "setData",
    "en-US": "setData"
  },
  {
    "key": "api_tree_set-visual",
    "zh-CN": "setVisual",
    "en-US": "setVisual"
  },
  {
    "key": "api_tree_swap",
    "zh-CN": "swap",
    "en-US": "swap"
  },
  {
    "key": "data-structure",
    "zh-CN": "数据结构",
    "en-US": "Data Structure"
  },
  {
    "key": "data-structure_array",
    "zh-CN": "数组",
    "en-US": "Array"
  },
  {
    "key": "data-structure_array_binary-search",
    "zh-CN": "fill",
    "en-US": "fill"
  },
  {
    "key": "data-structure_array_bubble-sort",
    "zh-CN": "fill",
    "en-US": "fill"
  },
  {
    "key": "data-structure_array_insertion-sort",
    "zh-CN": "fill",
    "en-US": "fill"
  },
  {
    "key": "data-structure_array_merge-sort",
    "zh-CN": "fill",
    "en-US": "fill"
  },
  {
    "key": "data-structure_array_merge-sort-once",
    "zh-CN": "fill",
    "en-US": "fill"
  },
  {
    "key": "data-structure_array_quick-sort",
    "zh-CN": "fill",
    "en-US": "fill"
  },
  {
    "key": "data-structure_array_quick-sort-once",
    "zh-CN": "fill",
    "en-US": "fill"
  },
  {
    "key": "data-structure_array_selection-sort",
    "zh-CN": "fill",
    "en-US": "fill"
  },
  {
    "key": "data-structure_graph",
    "zh-CN": "图",
    "en-US": "Graph"
  },
  {
    "key": "data-structure_graph_breadth-first-search",
    "zh-CN": "fill",
    "en-US": "fill"
  },
  {
    "key": "data-structure_graph_depth-first-search",
    "zh-CN": "fill",
    "en-US": "fill"
  },
  {
    "key": "data-structure_linked-list",
    "zh-CN": "链表",
    "en-US": "Linked List"
  },
  {
    "key": "data-structure_linked-list_create-list",
    "zh-CN": "fill",
    "en-US": "fill"
  },
  {
    "key": "data-structure_stack",
    "zh-CN": "栈",
    "en-US": "Stack"
  },
  {
    "key": "data-structure_stack_infix-expression-to-postfix",
    "zh-CN": "fill",
    "en-US": "fill"
  },
  {
    "key": "data-structure_stack_suffix-expression-evaluation",
    "zh-CN": "fill",
    "en-US": "fill"
  },
  {
    "key": "data-structure_tree",
    "zh-CN": "树",
    "en-US": "Tree"
  },
  {
    "key": "data-structure_tree_1-generate-multiple-tree",
    "zh-CN": "fill",
    "en-US": "fill"
  },
  {
    "key": "data-structure_tree_2-generate-multiple-tree",
    "zh-CN": "fill",
    "en-US": "fill"
  },
  {
    "key": "data-structure_tree_3-generate-multiple-tree",
    "zh-CN": "fill",
    "en-US": "fill"
  },
  {
    "key": "data-structure_tree_reverse-muiliple-tree",
    "zh-CN": "fill",
    "en-US": "fill"
  },
  {
    "key": "gallery",
    "zh-CN": "算法画廊",
    "en-US": "Algorithms Gallery"
  },
  {
    "key": "gallery_brute-force",
    "zh-CN": "蛮力",
    "en-US": "Brute Force"
  },
  {
    "key": "gallery_brute-force_fibonacci",
    "zh-CN": "fill",
    "en-US": "fill"
  },
  {
    "key": "gallery_brute-force_lexicographical-numbers",
    "zh-CN": "fill",
    "en-US": "fill"
  },
  {
    "key": "gallery_brute-force_three-steps-problem",
    "zh-CN": "fill",
    "en-US": "fill"
  },
  {
    "key": "gallery_decrease-and-conquer",
    "zh-CN": "减治",
    "en-US": "Decrease And Conquer"
  },
  {
    "key": "gallery_decrease-and-conquer_insertion-sort",
    "zh-CN": "fill",
    "en-US": "fill"
  },
  {
    "key": "gallery_divide-and-conquer",
    "zh-CN": "分治",
    "en-US": "Divide And Conquer"
  },
  {
    "key": "gallery_divide-and-conquer_merge-sort",
    "zh-CN": "fill",
    "en-US": "fill"
  },
  {
    "key": "gallery_divide-and-conquer_merge-sort-once",
    "zh-CN": "fill",
    "en-US": "fill"
  },
  {
    "key": "gallery_divide-and-conquer_quick-sort",
    "zh-CN": "fill",
    "en-US": "fill"
  },
  {
    "key": "gallery_divide-and-conquer_quick-sort-once",
    "zh-CN": "fill",
    "en-US": "fill"
  },
  {
    "key": "gallery_dynamic-programming",
    "zh-CN": "动态规划",
    "en-US": "Dynamic Programming"
  },
  {
    "key": "gallery_dynamic-programming_fibonacci",
    "zh-CN": "fill",
    "en-US": "fill"
  },
  {
    "key": "gallery_dynamic-programming_three-steps-problem",
    "zh-CN": "fill",
    "en-US": "fill"
  },
  {
    "key": "gallery_math",
    "zh-CN": "数学",
    "en-US": "Math"
  },
  {
    "key": "gallery_math_infix-expression-to-postfix",
    "zh-CN": "fill",
    "en-US": "fill"
  },
  {
    "key": "gallery_math_suffix-expression-evaluation",
    "zh-CN": "fill",
    "en-US": "fill"
  },
  {
    "key": "gallery_searching",
    "zh-CN": "搜索",
    "en-US": "Searching"
  },
  {
    "key": "gallery_searching_binary-search",
    "zh-CN": "fill",
    "en-US": "fill"
  },
  {
    "key": "gallery_searching_breadth-first-search",
    "zh-CN": "fill",
    "en-US": "fill"
  },
  {
    "key": "gallery_searching_depth-first-search",
    "zh-CN": "fill",
    "en-US": "fill"
  },
  {
    "key": "gallery_searching_tree-levelorder-traversal",
    "zh-CN": "fill",
    "en-US": "fill"
  },
  {
    "key": "gallery_searching_tree-postorder-traversal",
    "zh-CN": "fill",
    "en-US": "fill"
  },
  {
    "key": "gallery_searching_tree-preorder-traversal",
    "zh-CN": "fill",
    "en-US": "fill"
  },
  {
    "key": "gallery_sorting",
    "zh-CN": "排序",
    "en-US": "Sorting"
  },
  {
    "key": "gallery_sorting_bubble-sort",
    "zh-CN": "fill",
    "en-US": "fill"
  },
  {
    "key": "gallery_sorting_insertion-sort",
    "zh-CN": "fill",
    "en-US": "fill"
  },
  {
    "key": "gallery_sorting_merge-sort",
    "zh-CN": "fill",
    "en-US": "fill"
  },
  {
    "key": "gallery_sorting_merge-sort-once",
    "zh-CN": "fill",
    "en-US": "fill"
  },
  {
    "key": "gallery_sorting_quick-sort",
    "zh-CN": "fill",
    "en-US": "fill"
  },
  {
    "key": "gallery_sorting_quick-sort-once",
    "zh-CN": "fill",
    "en-US": "fill"
  },
  {
    "key": "gallery_sorting_selection-sort",
    "zh-CN": "fill",
    "en-US": "fill"
  }
]